[tool.basedpyright]
typeCheckingMode = "strict"
reportAny = "none" # Allow implicit any types
reportExplicitAny = "none" # Allow explicit any types

[tool.ruff.lint]
ignore = ["E701"] # Ignore multiple statements on one line
